### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-elemarmar#1]
Hola Elena, no te voy a pedir mejoras, prefiero que avances en otras cosas que te gusten.

Una sola cosa después de un `location.reload()` no hace falta poner nada más porque no tendrá efecto https://github.com/Adalab/modulo-2-evaluacion-intermedia-elemarmar/blob/master/main.js#L103.

Por lo demás un trabajo de 10, puedes y debes estar muy orgullosa...

**Comment by elemarmar** [comment]
¡¡Muchas gracias, Miguel!! Tomo nota ✏️
